### PR TITLE
using a builder to shrink final image size

### PR DESCRIPTION
**Pull request by aaronhmiller**
Using a builder and copying over compiled files shrinks final image from 367 MB down to 108 MB. Also added a .dockerignore to not bring in non-required files. Have a look at your convenience @erev0s

### CODE REVIEW

**Comment by aaronhmiller** [comment]
What do you think @erev0s ? Are there concerns you have that need addressing?

**Comment by erev0s** [comment]
hi @aaronhmiller , could you please clean it up so i can check it? It seems there is duplicate code

**Comment by aaronhmiller** [comment]
perhaps you're referring to 
```COPY . /vampi
WORKDIR /vampi```
which I don't see as duplicate code, just requirements to make things work.

**Comment by erev0s** [comment]
hey @aaronhmiller thank you for your patience.  Indeed you are right, I did not see the second `FROM` and though it was performing the same actions again.

**Pull request merged**
